import base64
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import Constants
from Google import Create_Service


class GmailAPI:

    def send_message_restore_password(self, email_to, user_password):
        service = Create_Service(Constants.CLIENT_SECRET_FILE, Constants.API_NAME, Constants.API_VERSION, Constants.SCOPES)

        mimeMessage = MIMEMultipart()
        mimeMessage['to'] = email_to
        mimeMessage['subject'] = Constants.SUBJECT

        emailMsg = """\
        Hello
        This message was automatically generated by StaffersBot

        This is your password:

        """ + user_password

        mimeMessage.attach(MIMEText(emailMsg, "Plain"))

        raw_str = base64.urlsafe_b64encode(mimeMessage.as_bytes()).decode()
        message = service.users().messages().send(userId='me', body={'raw': raw_str}).execute()
        print(message)