
import base64
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from Google import Create_Service

CLIENT_SECRET_FILE = 'credentials.json'
API_NAME = 'gmail'
API_VERSION = 'v1'
SCOPES = ['https://mail.google.com/']

service = Create_Service(CLIENT_SECRET_FILE, API_NAME, API_VERSION, SCOPES)


mimeMessage = MIMEMultipart()
mimeMessage['to'] = 'tairka.mail@gmail.com'
mimeMessage['subject'] = 'Test_Subject'

#<a href="http://www.realpython.com">Real Python</a>
text = """\
Hello,
This message was automatically generated to remind password of your account
"""

html = """\
<html>
  <body>
    <p>Hi,<br>
       How are you?<br>
       <a href="http://www.realpython.com">Real Python</a> 
       has many great tutorials.
    </p>
  </body>
</html>
"""

passwrod = "$#@$@"

emailMsg = """\
Hello
This message was automatically generated by StaffersBot

This is your password:

""" + passwrod

#mimeMessage.attach(MIMEText(text, text))

mimeMessage.attach(MIMEText(emailMsg, "Plain"))

#mimeMessage.attach(MIMEText(emailMsg, 'Test_containing_info'))

raw_str = base64.urlsafe_b64encode(mimeMessage.as_bytes()).decode()
message = service.users().messages().send(userId='me', body={'raw': raw_str}).execute()
print(message)